version: '2'
services:
  sshtunnel:
    image: ksurl/sshtunnel
    container_name: sshtunnel
    ports:
      - 80:80
    environment:
      - PUID=1000
      - PGID=1000
      - SSH_HOST=host
      - SSH_PORT=22
      - SSH_USERNAME=root
      #- SSH_PASSWORD=password
      - SSH_PRIVATE_KEY_PASSWORD=password
      - REMOTE_BIND_ADDRESSES=[("127.0.0.1", 80)]
      - LOCAL_BIND_ADDRESSES=[("0.0.0.0", 80)]
    volumes:
      - ./sshkey:/private.key
    restart: always
